# Generated by Django 4.0.3 on 2022-03-10 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_news_text_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='savers',
            field=models.ManyToManyField(blank=True, null=True, related_name='savers', to=settings.AUTH_USER_MODEL),
        ),
    ]
